In [1]:
import numpy as np

### NumPy
### Задание 1

In [16]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [17]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2

In [18]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [19]:
a_centered_ps = a_centered.T[0] @ a_centered.T[1]
a_centered_ps

8.0

In [20]:
a_centered_ps / (a_centered.shape[0] - 1)

2.0

### Pandas

### Задание 1

In [2]:
import pandas as pd

In [3]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
}) 
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [4]:
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

In [7]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3


In [9]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [14]:
authors_stat = authors_price.groupby('author_name').agg({'price': ['min', 'mean', 'max']})
authors_stat

price                 
              min        mean  max
author_name                       
Островский    290  330.000000  370
Тургенев      300  366.666667  450
Чехов         450  475.000000  500

In [17]:
authors_stat = authors_stat.rename(columns = {'min':'min_price', 'mean':'mean_price', 'max':'max_price'})
authors_stat

price                      
            min_price  mean_price max_price
author_name                                
Островский        290  330.000000       370
Тургенев          300  366.666667       450
Чехов             450  475.000000       500